---

- name: ensure tasks run only on selected os releases
  block:

    - name: install xone - xbox one and xbox series s|x gamepad drivers
      ansible.builtin.debug:
        msg: |
          -------------------------------------------------
          see https://github.com/medusalix/xone for details
          -------------------------------------------------
        verbosity: 0
      delegate_to: localhost
      run_once: true

    - name: prepare dependencies
      ansible.builtin.debug:
        msg: |
          --------------------------------------
          install and download xone dependencies
          --------------------------------------
        verbosity: 0
      delegate_to: localhost
      run_once: true

    - name: install xone dependencies
      ansible.builtin.package:
        name: "{{ xone.packages }}"
        state: latest

    - name: clear existing xone repository
      ansible.builtin.file:
        path: "{{ xone.repository_local }}"
        state: absent

    - name: clone xone repository
      ansible.builtin.git:
        repo: "{{ xone.repository_public }}"
        dest: "{{ xone.repository_local }}"

    - name: install xone
      ansible.builtin.debug:
        msg: |
          ---------------------------------
          build and install the xone driver
          ---------------------------------
        verbosity: 0
      delegate_to: localhost
      run_once: true

    - name: provide an error handler if the xone driver is already installed
      block:

        - name: install xone driver
          ansible.builtin.command:
            cmd: ./install.sh --release
            chdir: "{{ xone.repository_local }}"
          register: cmd_xone_install

      rescue:

        - name: uninstall existing xone driver
          ansible.builtin.command:
            cmd: ./uninstall.sh
            chdir: "{{ xone.repository_local }}"
          when:
            - cmd_xone_install is failed
            - "'already installed' in cmd_xone_install.stderr"

        - name: reinstall xone driver
          ansible.builtin.command:
            cmd: ./install.sh --release
            chdir: "{{ xone.repository_local }}"

    - name: download official firmware
      ansible.builtin.debug:
        msg: |
          ----------------------------------------------------------------
          download the official firmware for the microsoft xbox one dongle
          ----------------------------------------------------------------
        verbosity: 0
      delegate_to: localhost
      run_once: true

    - name: download firmware
      ansible.builtin.command:
        cmd: xone-get-firmware.sh --skip-disclaimer

  when: ansible_distribution == "Fedora"

...
