---

- name: ensure tasks run only on selected os releases
  block:

    - name: install xone dependencies
      ansible.builtin.package:
        name: "{{ xone.packages }}"
        state: latest

    - name: clear existing xone repository
      ansible.builtin.file:
        path: "{{ xone.repository_local }}"
        state: absent

    - name: clone xone repository
      ansible.builtin.git:
        repo: "{{ xone.repository_public }}"
        dest: "{{ xone.repository_local }}"

    - name: provide an error handler if the xone driver is already installed
      block:

        - name: install xone driver
          ansible.builtin.command:
            cmd: ./install.sh --release
            chdir: "{{ xone.repository_local }}"
          register: cmd_xone_install

      rescue:

        - name: uninstall existing xone driver
          ansible.builtin.command:
            cmd: ./uninstall.sh
            chdir: "{{ xone.repository_local }}"
          when:
            - cmd_xone_install is failed
            - "'already installed' in cmd_xone_install.stderr"

        - name: reinstall xone driver
          ansible.builtin.command:
            cmd: ./install.sh --release
            chdir: "{{ xone.repository_local }}"

    - name: download firmware
      ansible.builtin.command:
        cmd: xone-get-firmware.sh --skip-disclaimer

  when: ansible_distribution == "Fedora"

...
